### ISSUE TITLE
memize throws InvalidClassException when cached class has changed

### ISSUE THREAD

**Issue by k4200** [cb372/scalacache#39]
`memoize` throws java.io.InvalidClassException when the definition of a cached class has changed since it was cached. The version is 0.6.0.

## How to reproduce

Here are the steps to reproduce the issue (I borrow the code from issue 32):
* Compile and run the following code
```scala
case class User(id: Int, name: String)

object Test {

  import scalacache._
  import memoization._
  import redis._

  implicit val scalaCache = ScalaCache(RedisCache("localcache", 6379))

  def getUser(id: Int): User = memoize {
    User(id, "Taro")
  }

  def main(args: Array[String]): Unit = {
    getUser(1)
  }

}
```
* Make a small change to `User` class like the following:
```scala
case class User(id: Int, name: String, foo: String = "")
```
* Compile and run the code again.

## Stacktrace
Below is the error that I got:
```
[error] (run-main-2) java.io.InvalidClassException: User; local class incompatible: stream classdesc serialVersionUID = 869609799455012$
486, local class serialVersionUID = -576101910684720136
java.io.InvalidClassException: User; local class incompatible: stream classdesc serialVersionUID = 8696097994550122486, local class ser$
alVersionUID = -576101910684720136
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:617)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at scalacache.redis.RedisSerialization$class.deserialize(RedisSerialization.scala:59)
        at scalacache.redis.RedisCache.deserialize(RedisCache.scala:15)
        at scalacache.redis.RedisCache$$anonfun$get$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$1.apply(RedisCache.scala:33)
        at scalacache.redis.RedisCache$$anonfun$get$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$1.apply(RedisCache.scala:33)
        at scala.Option.map(Option.scala:146)
        at scalacache.redis.RedisCache$$anonfun$get$1$$anonfun$apply$1$$anonfun$apply$2.apply(RedisCache.scala:33)
        at scalacache.redis.RedisCache$$anonfun$get$1$$anonfun$apply$1$$anonfun$apply$2.apply(RedisCache.scala:31)
        at scalacache.redis.RedisCache.scalacache$redis$RedisCache$$withJedisClient(RedisCache.scala:81)
        at scalacache.redis.RedisCache$$anonfun$get$1$$anonfun$apply$1.apply(RedisCache.scala:31)
        at scalacache.redis.RedisCache$$anonfun$get$1$$anonfun$apply$1.apply(RedisCache.scala:31)
        at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$4.block(ExecutionContextImpl.scala:48)
        at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
        at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45)
        at scala.concurrent.package$.blocking(package.scala:123)
        at scalacache.redis.RedisCache$$anonfun$get$1.apply(RedisCache.scala:30)
        at scalacache.redis.RedisCache$$anonfun$get$1.apply(RedisCache.scala:30)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Thanks.

**Comment by cb372** [comment]
Thanks for the report.

Failing to deserialize after the class changes is expected, because we are using Java serialization. However, `memoize` should catch the error, log it and recover by running the method body and re-caching the result. Should be easy to fix.

By the way, when I get round to it I want to support pluggable serialization, so you can serialize to JSON/Kryo/whatever instead of using crappy Java serialization.

**Comment by k4200** [comment]
I tried the new version and it seems to be working. Thanks for the fix!
